"""Loads and caches track outline coordinates for the terminal viewer.

Reads from the pre-built circuits.json (generated by scripts/build_circuit_info.py).

Usage:
    loader = TrackLoader()
    points = loader.load(track_id=0)  # Melbourne — list of (x, z) tuples
"""

import json
from pathlib import Path

CIRCUITS_JSON = Path(__file__).resolve().parent.parent.parent / "race_engineer_hub" / "src" / "data" / "circuits.json"


class TrackLoader:
    """Loads and caches track outline coordinates."""

    def __init__(self):
        """Initialize with empty cache and load circuits data."""
        self._cache: dict[int, list[tuple[float, float]]] = {}
        self._circuits: dict = {}
        try:
            with open(CIRCUITS_JSON, encoding="utf-8") as f:
                self._circuits = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            pass

    def load(self, track_id: int) -> list[tuple[float, float]]:
        """Load track outline as a list of (x, z) world-space coordinates.

        Args:
            track_id: The m_trackId from the session packet.

        Returns:
            List of (x, z) tuples. Empty list if track not found.
        """
        if track_id in self._cache:
            return self._cache[track_id]

        circuit = self._circuits.get(str(track_id))
        if not circuit:
            self._cache[track_id] = []
            return []

        outline = circuit.get("outline", [])
        points = [(pt[0], pt[1]) for pt in outline]

        self._cache[track_id] = points
        return points
